[package]
name = "cache-size"
version = "0.3.5"
authors = ["Bernardo Meurer <meurerbernardo@gmail.com>"]
description = "A library for finding your L1/L2/L3 cache sizes "
repository = "https://github.com/lovesegfault/cache-size"
readme = "./README.md"
keywords = ["memory", "performance", "line", "size", "cache"]
categories = ["hardware-support", "memory-management"]
license = "BSD-3-Clause"

[badges]
travis-ci = { repository = "lovesegfault/cache-size", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
raw-cpuid = "7.0.3"

[profile.dev]
opt-level = 1
debug = true
rpath = false
lto = false
codegen-units = 16
panic = 'unwind'
incremental = true
overflow-checks = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
overflow-checks = false

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
overflow-checks = false
