[toolchain]
channel = "stable"
components = [
    "cargo",
    "clippy",
    "rust-analysis",
    "rust-src",
    "rust-std",
    "rustc",
    "rustfmt",
]
targets = [
    "x86_64-unknown-linux-musl",
    "x86_64-pc-windows-gnu",
    "x86_64-apple-darwin"
]

